[package]
name = "erp"
version = "0.4.2"
edition = "2024"

[lib]
name = "erp_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = "0.10"
anyhow = "1"
bincode = "1"
clap = { version = "4", features = ["derive"] }
dialoguer = "0.11"
hkdf = "0.12"
hmac = "0.12"
libc = "0.2"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
subtle = "2"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3"
